site_name: Ntools - Work in Progress
site_description: Software Tools Collection.
site_author: naz-hage
repo_name: ntools
repo_url: https://github.com/naz-hage/ntools
edit_uri: edit/main/docs/

theme:
  name: readthedocs
  language: en

nav:
  - Getting Started: 
    - Overview: index.md
    - Installation: installation.md
    - Practice: usage.md
    - Setup your project: setup.md
    - Build Types: buildtypes.md
    - Versioning: versioning.md
  - List of Tools:
      - Nbuild (nb.exe): ntools/nbuild.md
      - lf (lf.exe): ntools/lf.md
      - Nbackup (nbackup.exe): ntools/nbackup.md
      - Github Release : ntools/github-release.md
  - Custom Build Tasks:
      - Nbuild Tasks: ntools/nbuildtasks.md
  - Developer setup:
    - Version Automation Guide: version-automation-guide.md
    - Development Tools: ntools/ntools.md
    - ntools-scripts module:
      - Module: ntools/ntools-scripts-module.md
      - API: ntools/ntools-scripts-module-api.md
  - Build System Features:
    - Code Coverage: ntools/code-coverage.md
    - MSBuild Targets: ntools/nbuild-targets.md
  - atools:
    - Overview: atools/index.md
    - List of tools:
      - SDO (Simple DevOps Operations): atools/sdo.md
      - SDO Installation: atools/sdo-installation.md
      - Install NTools: atools/install-ntools.md
    - SDO Architecture: SDO_ARCHITECTURE.md
    - AzDO payloads: atools/azdo_payloads.md
